### ISSUE TITLE
Doesn't show pokemon that is a bit far away!

### ISSUE THREAD

**Issue by Nomi98** [kcaf/PokeRadar#13]
Somehow, whenever I get a little bit away from the pokemon, they disappear, even with the map draw in settings turned to max!

(If it's not an issue with the mod, I would like to know why this happens! Thank you!)

**Comment by kcaf** [comment]
the pokemon themselves disappear or the icons/dots on your radar disappear?

**Comment by kcaf** [comment]
As a follow up, I've noticed some servers with low performance don't send the data fast enough to keep up. Also it could be an issue with the number of entities Minecraft is keeping in your ram. Basically PokeRadar loops through your loaded entities and displays them all on radar. If the mod doesn't receive the entity from the server (due to lag) or the entity is not loaded in memory (dude to low pc performance), it won't show on the radar.

**Comment by Nomi98** [comment]
I guess it might be  a ram issue then.
