### ISSUE TITLE
Pink time 1.12.2

### ISSUE THREAD

**Issue by Snez0K** [kcaf/PokeRadar#41]
I running Forge Mod Loader version 14.23.2.2624 for Minecraft 1.12.2
Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_131, running on Windows 10
with Pixelmon reforged 1.12.2 (latest)
And all this mods:
![12312331231](https://user-images.githubusercontent.com/17159498/38873461-7d312b32-425e-11e8-931d-5510da3b006e.png)

![12312312312312](https://user-images.githubusercontent.com/17159498/38873240-fb6597d2-425d-11e8-8656-000a98aeaf88.png)

pls help to Fix this

**Comment by kcaf** [comment]
I notice you wrote in the discord that resetting the map textures didn't help. I don't know what to tell you then. It's obviously a bug, and one that is typically fixed by resetting the textures [https://github.com/kcaf/PokeRadar/wiki/Reset-corrupted-map]. But if that doesn't help, I don't know what else I can do for you.
